### PR TITLE
Enhance Ceph daemons and pools handling

### PR DESCRIPTION
**Pull request by NotTheEvilOne**
This PR enhances and fixes various details on Rook based Ceph daemon definition as well as MDS and RGW services. Therefore it depends on previous PRs to change the latest code base.

At the moment:
- It implements parsing and supporting Ceph erasure code profiles for OSD, MDS and RGW pools.
- It fixes the possible definition of k8s Rook labels for Ceph daemons implemented rudimentary before but basically unused.
- The PR enhances the workflow to be more resilient on interruptions

Depends: #54
Depends: #55
Depends: #57
Depends: #58
Depends: #59
Depends: #63
Depends: #66
Fixes: #65
Fixes: #70
Fixes: #71

### CODE REVIEW

**Comment by boekhorstb1** [comment]
Ok I tried running it on the testbed with this config (copied from config.osism.example.yml:

```
migration_modules:
- analyze_ceph
```

it seems to hang in `machine.py` on line 64 `try: self.next_state()` in the _execute method. `Date.pickle` file is empty, I have the feeling it is trying to recover a state that does not exist. 

This output from cli:

```
rookify                                                                                                                                                 
2024-08-14 09:00.25 [debug    ] Executing Rookify             
2024-08-14 09:00.26 [debug    ] Registering state 'PreflightAnalyzeCephHandler'
2024-08-14 09:00.26 [info     ] Execution started with machine pickle file
// here it freezes
```

**Comment by boekhorstb1** [comment]
after running the rookify from within the container I got this error (make run-rookify):


```
Traceback (most recent call last):
  File "/app/rookify/.venv/bin/rookify", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/rookify/.venv/lib/python3.12/site-packages/rookify/__main__.py", line 17, in main
    config = load_config("config.yaml")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/rookify/.venv/lib/python3.12/site-packages/rookify/yaml.py", line 22, in load_config
    yamale.validate(schema, data)
  File "/app/rookify/.venv/lib/python3.12/site-packages/yamale/yamale.py", line 45, in validate
    raise YamaleError(results)
yamale.yamale_error.YamaleError: Error validating data 'config.yaml' with schema '/app/rookify/.venv/lib/python3.12/site-packages/rookify/config.schema.yaml'
        rook.cluster.rgw_placement_label: Unexpected element
        rook.cluster.osd_placement_label: Unexpected element
        rook.cluster.mds_placement_label: Unexpected element
        rook.cluster.mon_placement_label: Unexpected element
        rook.cluster.mgr_placement_label: Unexpected element
````

this is some issue with paths. Because this works: 

```
yamale -s src/rookify/config.schema.yaml config.yaml                                                                 
Validating /home/worklark/dev/scs/rookify-enhance-ceph-pools/config.yaml...
Validation success! 
```

**Comment by boekhorstb1** [comment]
Ok another issue I got is this one:

config section:

```
general:
  machine_pickle_file: "data.pickle"

logging:
  level: DEBUG # level at which logging should start
  format:
    time: "%Y-%m-%d %H:%M.%S" # other example: "iso"
    renderer: console # or: json

ceph:
  config: ./.ceph/ceph.conf
  keyring: ./.ceph/ceph.client.admin.keyring

# fill in correct path to private key
ssh:
  private_key: ./.ssh/.id_rsa.regio-fast
  hosts:
    testbed-node-0:
      address: 192.168.16.10
      user: dragon
    testbed-node-1:
      address: 192.168.16.11
      user: dragon
    testbed-node-2:
      address: 192.168.16.12
      user: dragon

kubernetes:
  config: ./.k8s/config

rook:
  cluster:
    name: "osism-ceph"
    namespace: "rook-ceph"
    mds_placement_label: "node-role.osism.tech/rook-mds"
    mgr_placement_label: "node-role.osism.tech/rook-mgr"
    mon_placement_label: "node-role.osism.tech/rook-mon"
    osd_placement_label: "node-role.osism.tech/rook-osd"
    rgw_placement_label: "node-role.osism.tech/rook-rgw"
  ceph:
    image: quay.io/ceph/ceph:v18.2.1

migration_modules:
- migrate_mons
```


Error:

```
  File "/home/user/dev/scs/rookify-enhance-ceph-pools/src/rookify/modules/migrate_mons/main.py", line 37, in _migrate_mon
    result = self.ssh.command(
             ^^^^^^^^^^^^^^^^^
  File "/home/user/dev/scs/rookify-enhance-ceph-pools/src/rookify/modules/ssh.py", line 42, in command
    raise ModuleException(f"SSH command failed: {e}")
rookify.modules.exception.ModuleException: SSH command failed: Authentication failed.
```

NOTE: I am sure that login per ssh works as i tried it manually. Rather the error seems to be originating from the command here:

```
  result = self.ssh.command(
            mon["name"], "sudo systemctl disable --now ceph-mon.target"
        )
````

I guess something is wrong in my config maybe, not sure what it is.

**Comment by NotTheEvilOne** [comment]
An issue, initially found by @boekhorstb1, has been confirmed and traced down as some kind of race-condition issue. 

```
[...] -1 bluestore(/var/lib/ceph/osd/ceph-5/block) _read_bdev_label failed to open /var/lib/ceph/osd/ceph-5/block: (2) No such file or directory
[...] -1 bdev(0x557f1cd0c000 /var/lib/ceph/osd/ceph-5/block) open stat got: (1) Operation not permitted
```

We will track it as a separate issue (#70).

**Comment by NotTheEvilOne** [comment]
After re-execution of an started migration Ceph mon daemons are tried to be migrated again. (See #71)

**Comment by boekhorstb1** [comment]
if no rook operator is running in kubernetes, rookify will still execute right? Should there be a check to see if there is an operator at all, if not then error or log is given? For me rookify is running now without rook operator and is frozen, ceph as well

**Comment by NotTheEvilOne** [comment]
> if no rook operator is running in kubernetes, rookify will still execute right? Should there be a check to see if there is an operator at all, if not then error or log is given? For me rookify is running now without rook operator and is frozen, ceph as well @NotTheEvilOne (maybe that should be added to docs as well)

The existence of Rook ist validated by matching deployments for all namespaces with field `metadata.name=rook-ceph-operator` and label `operator=rook`. If a match is found we expect that Rook is completely installed as documented upstream. Obscure installations where this matches but the Rook operator still ignores our newly added resources later may be analyzed further.

**Comment by NotTheEvilOne** [comment]
All changes required for issues found are implemented and tested now.

**Review by boekhorstb1 — APPROVED** [review]
seems to be working in general, I think we should continue now and create issues if any other bugs are encoutnered

**Pull request merged**
