### PR TITLE
Create LICENSE

### LINKED ISSUE #16: [framework] license
We discussed with @fkr that an Apache2 license would make sense as rook is using this.

### PR DESCRIPTION
**Pull request by brueggemann**
We discussed with @fkr that an Apache2 license would make sense as rook is using this.

Closes #16

### CODE REVIEW

**Comment by fkr** [comment]
To give a tad more context: While we prefer the AGPLv3 license it makes sense to look at the ecosystem one is interacting with. In this case rook and the surrounding landscape makes heavy use of the Apache-2 license. As such in my opinion Apache 2 is the better fit for rookify.

**Review by fkr — APPROVED** [review]
LGTM!

**Comment by fkr** [comment]
@garloff do you agree with my assesment?

**Comment by garloff** [comment]
If we stand a chance for this tool to become integrated into rook, then ASL-2 would be a natural choice. If not, then I guess my preference would be LGPL-v2.1 which is the license of ceph itself and closer to our preferred license AGPL.

**Comment by fkr** [comment]
Discussion among @jschoone, @garloff and me resulted in Apache-2 being seen as OK.
Thanks @jschoone for pointing out the examples ceph-ansible and cephadm.

**Review by fkr — APPROVED** [review]

**Pull request merged**
